---
- name: Deploy files using Jinja2 template
  hosts: linux2
  become: true

  tasks:
    - name: Set /etc/hosts file content
      template:
        src: hosts.j2
        dest: /etc/hosts
        owner: root
        group: root
        mode: "0644"

