---
- name: Conditions and Handlers
  hosts: linux2
  become: true
  vars:
    web_users:
      - web_user1
      - web_user2

  tasks:
    - name: Database users present or absent
      user:
        name: "{{ item }}"
        state: absent
      # db_users is defined in group_vars/linux2
      loop: "{{ db_users }}"
      when: "'linux2' in group_names"
      notify: Print message

    - name: Web users present or absent
      user:
        name: "{{ item }}"
        state: absent
      loop: "{{ web_users  }}"
      when: "'linux2' in group_names"
      notify: Print message

  handlers:
    - name: Print message
      debug:
        msg: "Handler 'Print message' was notified. :)"
