---

- name: Error handling
  hosts: linux2
  become: true

  # Overwrite myFile to test: ansible-playbook playbook_errors.yml -e 'myFile=/etc/BLA'
  vars:
    - myFile: "/etc/passwd"

  tasks:
    - name: Example block - rescue - always
      block:
        - name: Block task tries to list file content
          shell:
            cmd: cat {{ myFile  }} >nul

      rescue:
        - name: Rescue task if block failed
          debug:
            msg: "Failed to cat {{ myFile }}. :("

      always:
        - name: Always task for final actions, like restart service
          debug:
            msg: "In each case run ..."

