---
- name: New user is created
  hosts: linux2
  become: true

  tasks:
    - name: Load variables from (maybe) encrypted file
      include_vars:
        file: secret_vars

    - name: Display encrypted variable
      debug:
        msg: "{{ secret }}"
#      no_log: true

    - name: User present or absent
      user:
        name: "{{ username['test']['uname'] }}"
        password: "{{ username['test']['password'] }}"
        comment: "{{ username['test']['description'] }}"
        state: absent

