---
# tasks file for users

# db_users and web_users are defined in group_vars/linux2

#  tasks:
    - name: Database users present or absent
      user:
        name: "{{ item }}"
        state: absent
      loop: "{{ db_users }}"
      when: "'linux2' in group_names"
      notify: Print message

    - name: Web users present or absent
      user:
        name: "{{ item }}"
        state: absent
      loop: "{{ web_users  }}"
      when: "'linux2' in group_names"
      notify: Print message
